version: "3"
services:
  app:
    container_name: express-mongo
    restart: on-failure
    build: ./
    ports:
      - "80:80"
    volumes:
      - .:/app
    links:
      - mongo
    command: npm run docker
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"